config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'static_page/home'

  resources :occupation_courts
  resources :partners
  resources :employees
  resources :employee_types
  resources :partner_states
  resources :people
  resources :courts

# root 'occupation_courts#index'
 root 'static_page#home'
#root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/court.rb
class Court < ApplicationRecord
    has_many :occupation_courts
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  before_action :set_court, only: [:show, :edit, :update, :destroy]

  # GET /courts
  # GET /courts.json
  def index
    @courts = Court.all
  end

  # GET /courts/1
  # GET /courts/1.json
  def show
  end

  # GET /courts/new
  def new
    @court = Court.new
  end

  # GET /courts/1/edit
  def edit
  end

  # POST /courts
  # POST /courts.json
  def create
    @court = Court.new(court_params)

    respond_to do |format|
      if @court.save
        format.html { redirect_to @court, notice: 'Court was successfully created.' }
        format.json { render :show, status: :created, location: @court }
      else
        format.html { render :new }
        format.json { render json: @court.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courts/1
  # PATCH/PUT /courts/1.json
  def update
    respond_to do |format|
      if @court.update(court_params)
        format.html { redirect_to @court, notice: 'Court was successfully updated.' }
        format.json { render :show, status: :ok, location: @court }
      else
        format.html { render :edit }
        format.json { render json: @court.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courts/1
  # DELETE /courts/1.json
  def destroy
    @court.destroy
    respond_to do |format|
      format.html { redirect_to courts_url, notice: 'Court was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_court
      @court = Court.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def court_params
      params.require(:court).permit(:nombre, :observacion)
    end
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/views/courts/_form.html.erb
<%= form_with(model: court, local: true) do |form| %>
  <% if court.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(court.errors.count, "error") %> prohibited this court from being saved:</h2>

      <ul>
      <% court.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :court_nombre %>
  </div>

  <div class="field">
    <%= form.label :observacion %>
    <%= form.text_field :observacion, id: :court_observacion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courts/edit.html.erb
<h1>Editing Court</h1>

<%= render 'form', court: @court %>

<%= link_to 'Show', @court %> |
<%= link_to 'Back', courts_path %>

app/views/courts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courts</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Observacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courts.each do |court| %>
      <tr>
        <td><%= court.nombre %></td>
        <td><%= court.observacion %></td>
        <td><%= link_to 'Show', court %></td>
        <td><%= link_to 'Edit', edit_court_path(court) %></td>
        <td><%= link_to 'Destroy', court, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Court', new_court_path %>

app/views/courts/new.html.erb
<h1>New Court</h1>

<%= render 'form', court: @court %>

<%= link_to 'Back', courts_path %>

app/views/courts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @court.nombre %>
</p>

<p>
  <strong>Observacion:</strong>
  <%= @court.observacion %>
</p>

<%= link_to 'Edit', edit_court_path(@court) %> |
<%= link_to 'Back', courts_path %>