config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'static_page/home'

  resources :occupation_courts
  resources :partners
  resources :employees
  resources :employee_types
  resources :partner_states
  resources :people
  resources :courts

# root 'occupation_courts#index'
 root 'static_page#home'
#root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/employee_types_controller.rb
class EmployeeTypesController < ApplicationController
  before_action :set_employee_type, only: [:show, :edit, :update, :destroy]

  # GET /employee_types
  # GET /employee_types.json
  def index
    @employee_types = EmployeeType.all
  end

  # GET /employee_types/1
  # GET /employee_types/1.json
  def show
  end

  # GET /employee_types/new
  def new
    @employee_type = EmployeeType.new
  end

  # GET /employee_types/1/edit
  def edit
  end

  # POST /employee_types
  # POST /employee_types.json
  def create
    @employee_type = EmployeeType.new(employee_type_params)

    respond_to do |format|
      if @employee_type.save
        format.html { redirect_to @employee_type, notice: 'Employee type was successfully created.' }
        format.json { render :show, status: :created, location: @employee_type }
      else
        format.html { render :new }
        format.json { render json: @employee_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_types/1
  # PATCH/PUT /employee_types/1.json
  def update
    respond_to do |format|
      if @employee_type.update(employee_type_params)
        format.html { redirect_to @employee_type, notice: 'Employee type was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_type }
      else
        format.html { render :edit }
        format.json { render json: @employee_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_types/1
  # DELETE /employee_types/1.json
  def destroy
    @employee_type.destroy
    respond_to do |format|
      format.html { redirect_to employee_types_url, notice: 'Employee type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_type
      @employee_type = EmployeeType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_type_params
      params.require(:employee_type).permit(:desc)
    end
end

app/helpers/employee_types_helper.rb
module EmployeeTypesHelper
end

app/views/employee_types/_form.html.erb
<%= form_with(model: employee_type, local: true) do |form| %>
  <% if employee_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee_type.errors.count, "error") %> prohibited this employee_type from being saved:</h2>

      <ul>
      <% employee_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc, id: :employee_type_desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employee_types/edit.html.erb
<h1>Editing Employee Type</h1>

<%= render 'form', employee_type: @employee_type %>

<%= link_to 'Show', @employee_type %> |
<%= link_to 'Back', employee_types_path %>

app/views/employee_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employee Types</h1>

<table>
  <thead>
    <tr>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_types.each do |employee_type| %>
      <tr>
        <td><%= employee_type.desc %></td>
        <td><%= link_to 'Show', employee_type %></td>
        <td><%= link_to 'Edit', edit_employee_type_path(employee_type) %></td>
        <td><%= link_to 'Destroy', employee_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee Type', new_employee_type_path %>

app/views/employee_types/new.html.erb
<h1>New Employee Type</h1>

<%= render 'form', employee_type: @employee_type %>

<%= link_to 'Back', employee_types_path %>

app/views/employee_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Desc:</strong>
  <%= @employee_type.desc %>
</p>

<%= link_to 'Edit', edit_employee_type_path(@employee_type) %> |
<%= link_to 'Back', employee_types_path %>